# Generated by Django 4.1.12 on 2023-10-16 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='phone',
            field=models.CharField(error_messages={'unique': 'Phone is already used'}, max_length=15, unique=True),
        ),
    ]
